name: Docker Check

on:
  - push

jobs:
  hadolint:
    name: hadolint DockerFile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile # チェックするDockerファイル

